spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-KGMCNEU\SQLEXPRESS;databaseName=Musica_Thymeleaf
    username: DESKTOP-KGMCNEU\adria
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
jpa:
  properties:
    hibernate:
      show_sql: true
      hbm2ddl:
        auto: update